name: Issue assignment

on:
    pull_request:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Weekly auto assign code buddies'
              uses: Myztiq/github-assign@0.0.3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  assignees: Myztiq, Myztiq
